### ISSUE TITLE
Move Table class variables to private

### ISSUE THREAD

**Issue by lordent** [kayak/pypika#120] opened 2018-04-21 16:59 UTC
For example, this condition causes an AttributeError: 'bool' object has no attribute 'fields'
> .where(information_schema.table_name == 'public')

```
class Table(Selectable):
    def __init__(self, name, schema=None, alias=None):
        super(Table, self).__init__(alias)
        self.__table_name = name
        self.__schema = schema
```

**Comment by twheys** [comment] 2018-04-23 08:36
This is a duplicate of https://github.com/kayak/pypika/issues/13 that I hadn't gotten around to earlier. Will fix this shortly.

**Closed** 2018-04-23 09:51 UTC

**Comment by lordent** [comment] 2018-04-23 16:49
@twheys thx, good job!

**Comment by twheys** [comment] 2018-04-25 11:02
Published 0.14.2
