### ISSUE TITLE
How to add subqueries with alias?

### ISSUE THREAD

**Issue by Onalu** [kayak/pypika#126] opened 2018-05-17 07:56 UTC
Hello,

I have got some problems with subqueries. I tried to adding subqueries by passing a Query object to from_ method of another one. It puts a generated alias sq0  like that. Is there a way to use a custom alias instead of sq0? I could not find it.

I also tried passing SQL text to Table class as table name and giving alias. This actually produces the result I want but I am not sure this it is an intended way to use Table class. This type of usage would make sense with WITH clause but it is not supported. 

Thanks

**Comment by twheys** [comment] 2018-05-19 07:45
This should be fixed by https://github.com/kayak/pypika/pull/127

Can you give it a try and let me know if there are any issues?

**Comment by Onalu** [comment] 2018-05-21 06:09
@twheys I am talking about a different problem. It adds sq0, sq1 etc.  as subquery alias but I want to give an alias (i.e. 'users_filtered' ) myself instead of these.

**Comment by twheys** [comment] 2018-07-24 11:01
I think this is a bug where the alias set is overwritten by a generated one. Will take a look.

**Comment by twheys** [comment] 2018-08-08 11:11
Is this still relevant? I am unable to reproduce it. If you're still having trouble with it, please submit some test case examples. I am going to add some unit tests to cover the case you described.

**Comment by Onalu** [comment] 2018-08-09 07:14
Hello,

I wasn't reporting a bug actually. I was asking a question to how to give alias to a subquery. I can see that it is possible with `as_` method from Term class in the test cases you have updated. I wasn't aware of that method. So, you can close the issue.

Thank you for time and help.

**Comment by twheys** [comment] 2018-08-09 09:55
Ah, sorry i was confused because there was actually recently an actual bug regarding this that I don't remember explicitly fixing, although it is fixed now.

**Closed by twheys** 2018-08-09 09:55 UTC
